### PR TITLE
Stop relying on obsolete parseTime function

### LINKED ISSUE #12: can't compile with ghc-9.2.1 alpha2
```
[1 of 1] Compiling Data.DateTime    ( src/Data/DateTime.hs, dist/build/Data/DateTime.o, dist/build/Data/DateTime.dyn_o )

src/Data/DateTime.hs:119:17: error:
    • Variable not in scope:
        parseTime :: TimeLocale -> String -> String -> Maybe DateTime
    • Perhaps you meant ‘parseTimeM’ (imported from Data.Time.Format)
    |
119 | parseDateTime = parseTime defaultTimeLocale
    |                 ^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by l29ah**
fixes https://github.com/stackbuilders/datetime/issues/12

### CODE REVIEW

**Comment by Centeno448** [comment]
Closing because library is being deprecated.
