### ISSUE TITLE
can't compile with ghc-9.2.1 alpha2

### ISSUE THREAD

**Issue by l29ah** [stackbuilders/datetime#12]
```
[1 of 1] Compiling Data.DateTime    ( src/Data/DateTime.hs, dist/build/Data/DateTime.o, dist/build/Data/DateTime.dyn_o )

src/Data/DateTime.hs:119:17: error:
    • Variable not in scope:
        parseTime :: TimeLocale -> String -> String -> Maybe DateTime
    • Perhaps you meant ‘parseTimeM’ (imported from Data.Time.Format)
    |
119 | parseDateTime = parseTime defaultTimeLocale
    |                 ^^^^^^^^^
```

**Comment by emberdart** [comment]
Looks like it's been broken for a while. parseTime isn't available since time 1.9.3.

**Comment by Centeno448** [comment]
Closing because library is being deprecated.

**Comment by emberdart** [comment]
Oh? In favour of what? Or is everything here already in core libs?

**Comment by JoseLion** [comment]
@danwdart, thanks for reaching out. Even though not everything is on the core libs, we're deprecating this library in their favor. This library is built on top of the core libs, and most of the helper functions missing are simple and could be implemented on userland with little effort.

However, we appreciate you reaching out to us and would like to know how you use this library or the use case you see on it. That can help us understand if there's a better approach we can take here or a different solution we could work on 🙂

**Comment by JoseLion** [comment]
We're moving forward with the deprecation process. However, if anyone feels the library is still relevant, you can always reach out to info@stackbuilders.com

**Comment by emberdart** [comment]
Thanks. I use fromGregorian and addSeconds. Hadn't realised if there was a newer way of doing it and that seemed to do the job at the time. This is probably now in Data.Time from time, I suppose.
